---
# tasks file for webserver


  - name: install webserver
    package:
       name: "{{ package_name }}"
       state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: install app
    apt:
       name: apache2
       state: present
    when: ansible_facts['os_family'] == "Debian"


  - name: manage service
    service:
       name: "{{ service_name }}"
       state: started

  - name: deploy site
    copy:
       src: index.html
       dest: /var/www/html/
    notify:
       - restart_webservice

  - include: user.yml



